version: '3.7'
services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 8051:80
        volumes:
            - ./:/var/www/fmanager
            - .docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - l_net

    fmanager:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            SERVICE_NAME: fmanager
            SERVICE_TAGS: dev
        working_dir: /vae/www/fmanager
        volumes:
            - ./:/var/www/fmanager
        networks:
            - l_net

    mysql:
        image: mysql:8.3
        ports:
            - 33096:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=fmanager
        volumes:
            - .docker/data/dbdata:/var/lib/mysql
        networks:
            - l_net

networks:
    l_net:
        driver: bridge
